virtual_store/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  resources :products
end

virtual_store/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

virtual_store/app/models/product.rb
class Product < ApplicationRecord
  enum status: [:available, :reserved, :sold]
  enum tax: {tax_exempt: 0, normal_tax: 15, import_tax: 25}

  def total
    ((price * (100 + tax)).to_f / 100.0).round
  end

  def formatted_price
    extra_zero = ((price % 100) <  10)? "0" : ""
    "$" + (price / 100).to_s + "." + extra_zero + (price % 100).to_s
  end

  def formatted_total
    extra_zero = ((total % 100) <  10)? "0" : ""
    "$" + (total / 100).to_s + "." + extra_zero + (total % 100).to_s
  end

end

virtual_store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

virtual_store/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(sanitized_params)
    # Redo form if bad inputs:
    unless @product.name.length > 0
      flash[:alert] = "You must name the product."
      render :new
      return
    end
    unless @product.price && @product.price > 0
      flash[:alert] = "No freebies!"
      @product.price = nil # delete bad user set value if necessary
      render :new
      return
    end
    # Set defaults
    unless @product.tax
      @product.normal_tax!
    end
    # Set product to available
    @product.available!
    redirect_to products_url
  end

private

  def sanitized_params
    params.require(:product).permit(:name, :description, :price, :tax)
  end

end

virtual_store/app/helpers/application_helper.rb
module ApplicationHelper
end

virtual_store/app/helpers/products_helper.rb
module ProductsHelper
end

virtual_store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VirtualStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

virtual_store/app/views/products/_product_form.html.erb
<%= form_for product do |f| %>
  <table>
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    </tr><tr>
      <td><%= f.label :price %></td>
      <td><%= f.number_field :price %></td>
    </tr><tr>
      <td>Tax</td>
      <td>
        <%= radio_button_tag(:'product[tax]', 0) %>
        <%= label_tag(:'product[tax]', "Exempt") %>
        <%= radio_button_tag(:'product[tax]', 15) %>
        <%= label_tag(:'product[tax]', "Normal") %>
        <%= radio_button_tag(:'product[tax]', 25) %>
        <%= label_tag(:'product[tax]', "Import") %>
      </td>
    </tr>
    <tr>
      <td><%= label_tag(:quantity, "Quantity") %></td>
      <td><%= number_field_tag(:quantity) %></td>
    </tr><tr>
      <td><%= label_tag(:'product[description]', "Description") %></td>
      <td><%= text_area_tag(:'product[description]', "", size: '50x5') %></td>
    </tr>
  </table>
  <%= f.submit %>


<% end %>

virtual_store/app/views/products/_product_table.erb
<table>
  <tr>
    <th>Item</th><th>Price</th><th>Quantity</th><th></th>
  </tr>

  <% products.each do |product| %>
  <tr>
    <td><%= link_to "product.name", product_url(product.id) %></td><td><%= product.formatted_price %></td><td></td><td></td>
  </tr>
  <% end %>
</table>

virtual_store/app/views/products/index.html.erb
<h1>Inventory</h1>


<%= render 'product_table', products: @products %>

virtual_store/app/views/products/new.html.erb
<%= render 'product_form', product: @product%>